# application-cloud.properties

# Config Server
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=1000

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.health.circuitbreakers.enabled=true

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.kafkaProducer.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaProducer.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaProducer.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafkaProducer.permitted-number-of-calls-in-half-open-state=3